sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=terradue/nb-burned-area-delineation
    - VERSION=0.3

script:
  - docker build -f Dockerfile --no-cache --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"
deploy:
  provider: script
  script: 
    - docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"
  on:
    branch: master
